### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by chchrist** [mhadidg/software-architecture-books#2]
Thank you for this great list of software architecture books!
It would be great if you also enabled github pages for the repository with the "architect" theme?

**Comment by mhadidg** [comment]
Hello @chchrist,

Thanks for the suggestion.
I will definitely consider it. I don't have any experience with Github Pages (hence static site generators). I have to read about it and see if there are better alternatives.

I just look up the architect theme though, looks nice =)

**Comment by chchrist** [comment]
Github is taking care of the whole static site generation for you. You just need to enable it.
Also if the ISBNs of each book are added people can easily import the list in their good reads account https://www.goodreads.com/review/import

**Comment by mhadidg** [comment]
I will add the ISBN column in the next few days. I think it's a good idea not just for the import action on Goodreads, but for anyone that might need those ISBNs to fetch additional information with scripts.

Thank you for the suggestion, again.

**Comment by chchrist** [comment]
Hey, @mhadidg I'll make a pull request for these ISBNs. I added them for me.

**Comment by mhadidg** [comment]
That's great. Thank you.
