### ISSUE TITLE
Pragmatic Programmer

### ISSUE THREAD

**Issue by p-mcgowan** [mhadidg/software-architecture-books#6]
A classic, one of the best books I've read on software. I believe it fits the criteria.

https://www.goodreads.com/book/show/4099.The_Pragmatic_Programmer

**Comment by mhadidg** [comment]
I deliberately exclude it. I thought the book doesn't discuss architectural concerns. 

I just reviewed the content and changed my mind. I will include it under the general section in the next update. Meanwhile, you may create a pull request for it if you want.

Thank you for the suggestion.

**Comment by p-mcgowan** [comment]
Thanks! Yeah I suspected that might be the case at first, it's more of a general overview than architectural for sure, but as I read down the list I saw the general section. I'll toss up a PR soon then.
