### ISSUE TITLE
The Cloud Service Evaluation Handbook: How to Choose the Right Service

### ISSUE THREAD

**Issue by eeskam** [mhadidg/software-architecture-books#7]
The Cloud Service Evaluation Handbook: How to Choose the Right Service by Scott Feuless would be an excellent addition to the cloud engineering section.  Subtle architecture or SLA decisions can dramatically impact pricing, performance, scalability, resilience and more.

SLAs should be the *starting* point for any cloud computing project - unfortunately they are usually an after thought or glossed over.

**Comment by mhadidg** [comment]
It looks like a good one. Yet, [the book profile on Goodreads](https://www.goodreads.com/book/show/31387619) doesn't match [the inclusion criteria](https://github.com/mhadidg/software-architecture-books#inclusion-criteria).

**Comment by mhadidg** [comment]
Thanks for the suggestion though.
