### ISSUE TITLE
Hands-On Design Patterns with C# and .NET Core

### ISSUE THREAD

**Issue by ptjuanramos** [mhadidg/software-architecture-books#8]
I'm not sure if this is too language specific.

**Comment by mhadidg** [comment]
[The book profile on Goodreads](https://www.goodreads.com/book/show/41729534) doesn't match [the inclusion criteria](https://github.com/mhadidg/software-architecture-books#inclusion-criteria). Using C# and .NET core doesn't exclude the book from this list if the author use these technologies as a tool to express his idea.

Thanks for the suggestion though.

**Comment by mhadidg** [comment]
[The book profile on Goodreads](https://www.goodreads.com/book/show/41729534) doesn't match [the inclusion criteria](https://github.com/mhadidg/software-architecture-books#inclusion-criteria). Using C# and .NET core doesn't exclude the book from this list if the author uses these technologies as a tool to express his idea.

Thanks for the suggestion though.
